### ISSUE TITLE
[Usuário][Email][Confirmação] - Documentação do endpoint para confirmação via e-mail

### ISSUE THREAD

**Issue by kvnbg** [devhatt/octopost-backend#105]
Criar documentacao para confirmação de email do usuário que receberá um `token` via query param

Sugestões:
### Requisição
- Rota: /auth/confirmation?token=
- Método HTTP: GET

### Resposta
- Código HTTP: 204

**Comment by Lukasveiga** [comment]
Eu quero!!!
