### ISSUE TITLE
[Usuário][Contas][Deletar] - Criar documentação para apagar conta da rede social do usuário

### ISSUE THREAD

**Issue by kvnbg** [devhatt/octopost-backend#106]
Criar endpoint para exclusao da conta de rede social do usuario

Sugestões:
### Requisição
- Rota: /users/{userId}/accounts/{accountId}
- Método HTTP: DELETE
### Resposta
- Código HTTP: 204

**Comment by thiagoCalazans-dev** [comment]
eu quero!!!
