### ISSUE TITLE
[Usuário][Cadastro] - Ajustar documentação openapi do endpoint de Cadastro de Usuário

### ISSUE THREAD

**Issue by Lukasveiga** [devhatt/octopost-backend#117]
- Ajustar o endpoint de cadastro do usuário no arquivo openapi/main.yaml. Remover a repetição do 'api' no path do endpoint.
![Captura de tela de 2024-06-06 21-54-58](https://github.com/devhatt/octopost-backend/assets/62577969/95ac4668-9afc-4845-87a0-6bcf6449663d)

**Comment by davidspader** [comment]
Eu quero!!!
