### ISSUE TITLE
[Usuário][Cadastro] - Ajustar documentação openapi do endpoint de Cadastro de Usuário

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost-backend#14]
Ajustar a documentação da api na pasta `openapi` do endpoint referente ao Cadastro de usuários para abranger os seguintes dados:

### Requisição
- Rota: /api/users
- Método HTTP: POST
- Corpo da Requisição: 
- Módulo: User

``` json
{
  "name": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com",
  "password": "001@Mypassword",
  "repeatPassword": "001@Mypassword"
}
```

### Resposta
- Código HTTP: 201
- Corpo da resposta: N/A

### Referência: 
- [Documentação](https://swagger.io/docs/specification/about/)
- [Exemplo](https://editor.swagger.io)

**Comment by Frompaje** [comment]
Eu quero!!!
