### ISSUE TITLE
[Auth][Login] - Criar documentação openapi do endpoint de Login

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost-backend#15]
Adicionar no swagger da API o endpoint referente ao Login de usuário

### Requisição
- Rota: /auth/login
- Módulo: Authentication
- Método HTTP: POST
- Corpo da Requisição: 
``` json
{
  "username": "johndoe123",
  "password": "001@Mypassword",
}
```

### Resposta
- Código HTTP: 200
- Corpo da resposta:
``` json
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
  "issuedAt": "1714233677",
  "expireAt": "1714237277"
}
```

### Referência: 
- [Documentação](https://swagger.io/docs/specification/about/)
- [Exemplo](https://editor.swagger.io)

**Comment by Lukasveiga** [comment]
eu quero!!!
