### ISSUE TITLE
modularizar a porta exposta da api no docker compose

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost-backend#156]
Atualmente as portas da api estão fixas e iss não pode acontecer, elas devem variar de acordo com a porta da aplicação pela variável port no .env 

![Image](https://github.com/user-attachments/assets/296c98cf-afae-4339-a738-77599d93744d)

**Comment by MatheusVinicius77** [comment]
quero

**Comment by MatheusVinicius77** [comment]
eu quero!!!
