### ISSUE TITLE
[Usuário][Consulta] - Criar documentação do endpoint de consulta usuario por id

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost-backend#16]
Adicionar a documentação do endpoint na pasta `openapi` referente a consulta de usuário por id:

### Requisição
- Rota: /users/:id
- Módulo: User
- Método HTTP: GET
- Header:
  - Authorization

### Resposta
- Código HTTP: 200
- Corpo da resposta:
```json
{
  "id": "1",
  "name": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com"
}
```

### Referência: 
- [Documentação](https://swagger.io/docs/specification/about/)
- [Exemplo](https://editor.swagger.io)

**Comment by JpBurgarelli** [comment]
eu quero!!!
