### ISSUE TITLE
Mover fluxo de login para um service

### ISSUE THREAD

**Issue by k1nha** [devhatt/octopost-backend#164]
Mover o fluxo de login, hoje está no controller, para um service novo, implementando os testes necessários (controller, service)

```ts
login: AsyncRequestHandler = (req, res) => {
    const authorization = req.headers.authorization;

    if (!authorization) {
      return res.status(401).json({ message: 'Unauthorized' });
    }

    const [, token] = authorization.split(' ');

    const payload = jwt.verify(token, 'secret_key') as TokenPayload;

    const url = generateAuthURL({ id: payload.userId });

    return res.json(url);
  };
```

**Comment by LFelipeP** [comment]
Tenho interesse em atuar nessa issue

**Comment by juliaam** [comment]
> Tenho interesse em atuar nessa issue

Manito, faz um novo comentário digitando 
`eu quero!!!`

somente com esse texto, com os três !!!, assim a task vai ser sua, se puder, entra lá no discord https://discord.gg/FjXw4pf4

**Comment by LFelipeP** [comment]
eu quero!!!

**Comment by DominMFD** [comment]
eu quero!!!
