### ISSUE TITLE
[Test] Criar Teste para authFilterMiddleware

### ISSUE THREAD

**Issue by Frompaje** [devhatt/octopost-backend#184]
Teste unitário para validar o funcionamento do middleware authFilterMiddleware, especialmente a lógica que envolve a criação de authJwt a partir de authJwtFactory e o uso de filter da classe AuthFilter.

![Image](https://github.com/user-attachments/assets/1c3c99f7-b2d2-49d8-bf78-78a10c9e3306)

**Comment by juliaam** [comment]
Eu quero!!!
