### ISSUE TITLE
[Usuário][Cadastro] - Criação da validação do payload de entrada para cadastro do usuário

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#23]
Deve-se criar uma validação do payload de entrada na API, afim de garantir que os dados obrigatórios estão preenchidos antes de começarmos a processar a requisição.

Na API iremos utilizar a biblioteca Joi para realizar validação de JSON schema. 

Precisamos ter as seguintes validações:
- `GERAL`: todos os campos deve-se validar se não são vazios ou nulos.
- `name`: se contém pelo menos 3 caracteres.
- `username`:  se contém pelo menos 3 caracteres.
- `email`: se está no formato de e-mail válido.
- `password`: se atende aos critérios minimos (1 letra maiúscula, 1 caracter especial, minimo de 8 caracteres).
- `repeatPassword`: se atende aos critérios minimos (1 letra maiúscula, 1 caracter especial, minimo de 8 caracteres).

### Payload de entrada
``` json
{
  "name": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com",
  "password": "001@Mypassword",
  "repeatPassword": "001@Mypassword"
}
```

**Comment by thiagoCalazans-dev** [comment]
EU QUERO!!!
