### ISSUE TITLE
[Usuário][Cadastro] - Criar Service com regra de negócio

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#24]
Ajustar a validação do UseCreateService para tratar os dados que vem do frontend.(Você deve seguir a documentação do openapi).

Antes de criarmos um novo usuário na aplicação, no `UserServiceCreate`, devemos garantir também que `password` e `repeatPassword` são iguais, e configurar a tabela para que não haja nenhum username/email igual.

Os erros jogados devem ser tratados corretamente e retornarem mensagens de erro.

**Comment by Clerijr** [comment]
tyi: A tratativa de repeatPassword já está sendo realizada através da PR https://github.com/devhatt/octopost-backend/pull/64. O objetivo desta PR é tratar uniques username e email.
