### ISSUE TITLE
[Auth] - Criar módulo de autenticação JWT e middleware de verificação

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#26]
Precisamos de uma classe responsável pela criação, verificação e parseamento de tokens JWT.
Esse módulo de JWT ficará dentro de `shared/infra` e deverá conter testes unitários mockando o JWT.

Nessa classe deverá conter os métodos de:
- `create()`: responsável por criar um token JWT válido para aplicação
- `refreshToken()`: irá criar um novo token JWT válido
- `parseToken()`: irá retorna o payload do token 

O Middleware deve ser responsável por utilizar essa classe JWT para verificar se o usuário está ou não autenticado baseando-se no token JWT, ficando dentro da pasta compartilhada `src/middlewares`, já que é um middleware de uso geral.

**Comment by yuri-silveiraa** [comment]
eu quero!!!
