### ISSUE TITLE
[Email] - Criação de módulo que controle o envio de emails

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#27]
Criação de um módulo agnóstico de envio de email dentro da `src/shared/infra/email`, ele deverá expor métodos responsáveis pelo envio de um email a partir de um template pronto. 

A ideia é que essa abstração tenha uma método de envio que recebe um `template` e `recipient` e trate todo o processo de envio de email.

Se variáveis de ambiente, ou pacotes externos precisarem ser instalados para que essa operação funcione e você tiver alguma dúvida, podemos discutir sobre isso posteriormente.

**Comment by yan-pi** [comment]
Eu quero!!!
