### ISSUE TITLE
[Auth][Login] - Expor endpoint para realizar login

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#32]
Depende da issue: #15 

Criar um `AuthController` que terá a rota `POST /auth/login` recebendo o `username` e `password` do usuário que irá logar.

Sugestões:
### Requisição
- classe: AuthController
- Rota: /api/auth/login
- Método HTTP: POST
- Corpo da Requisição: 
``` json
{
  "username": "johndoe123",
  "password": "001@Mypassword",
}
```

### Resposta
- Código HTTP: 200
- Corpo da resposta:
``` json
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
  "issuedAt": "1714233677",
  "expireAt": "1714237277"
}
```

**Comment by Lukasveiga** [comment]
Eu quero!!!
