### ISSUE TITLE
[Auth][Login] - Criação da validação do payload de entrada para login

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#33]
Depende #32 
Deve-se criar uma validação do payload de entrada na API, afim de garantir que os dados obrigatórios estão preenchidos antes de começarmos a processar a requisição

Na API iremos utilizar a biblioteca Joi para realizar validação de JSON schema. 

Precisamos ter as seguintes validações:
- `GERAL`: todos os campos deve-se validar se não são vazios ou nulos

### Payload de entrada
``` json
{
  "username": "johndoe123",
  "password": "001@Mypassword"
}
```

**Comment by Lukasveiga** [comment]
Eu quero!!!
