### ISSUE TITLE
[Auth][Login] - Criar um service para realizar o login do Usuario

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#34]
O `AuthService` deverá seguir os seguintes passos para verificar se as informações passadas são válidas e gerar um token JWT para o usuário:

1. Verificar se o username existe na base de dados
3. Verificar se o `password` recebido, após a criptografia, é igual ao que está salvo no banco de dados.
4. Recuperar as informações do usuário da base de dados
5. Gerar o token JWT com as informações do usuário (`id`)

**Comment by thiagoCalazans-dev** [comment]
EU QUERO!!!
