### ISSUE TITLE
[Usuário][Consulta] - Expor endpoint de consulta do usuário pelo id

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#36]
Criar um `UserController` que terá a rota `GET /users/` recebendo o `id` via Query Parameter. 
No controller deve validar se o query param `id` possui valor válido.

Sugestões:
### Requisição
- classe: UserController
- Rota: /api/users/:id
- Método HTTP: GET

### Resposta
- Código HTTP: 200
- Corpo da resposta:
```json
{
  "id": "1",
  "name": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com"
}
```

**Comment by Alecell** [comment]
eu quero!!!

**Comment by Alecell** [comment]
eu quero!!!

**Comment by nathalia-84** [comment]
eu quero!!!
