### ISSUE TITLE
[Usuário][Contas] - Expor o endpoint para consulta de contas de redes sociais do usuário logado

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#39]
Depende #17 
Criar `UserController` com método `getAccounts()` que irá receber um query parameter `id`, com a informação do id do usuário.

Sugestões:
### Requisição
- Rota: /api/users/:id/accounts
- Método HTTP: GET
- Header:
  - Authorization

### Resposta
- Código HTTP: 200
- Corpo da resposta:
``` json
[
   {
      "id":"d215f543-f05c-40c2-a665-1a98f108bb5c",
      "avatarUrl":"https://backend/files/image.png",
      "socialMedia":{
         "id":1,
         "name":"Facebook"
      }
   }
]
```

**Comment by TheGzuckert** [comment]
Eu quero!!!
