### ISSUE TITLE
[SocialMedia][Lista] - Criar documentação do endpoint para listar as redes sociais disponiveis

### ISSUE THREAD

**Issue by kvnbg** [devhatt/octopost-backend#61]
Adicionar a documentação do endpoint na pasta `openapi` referente a consulta de redes sociais disponíveis para integração no Octopost

### Requisição
- Rota: /socialmedias
- Módulo: SocialMedias
- Método HTTP: GET
- Header:
  - Authorization

### Resposta
- Código HTTP: 200
- Corpo da resposta:
```json
[
    {
       "id": 1,
       "name": "Facebook"
    },
    {
       "id": 2,
       "name": "Instagram"
    }
]
```

### Referência: 
- [Documentação](https://swagger.io/docs/specification/about/)
- [Exemplo](https://editor.swagger.io)

**Comment by Lukasveiga** [comment]
Eu quero!!!
