### ISSUE TITLE
[Usuário][Cadastro] - Expor endpoint para cadastro de usuário

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#8]
Haverá uma rota chamada `POST /users/`, essa rota receberá quatro valores `email`, `username`, `password` e `passwordRepeat`.

### Requisição
- modulo: user
- serviço: UserCreateService
- classe: UserController
- Rota: /users
- Método HTTP: POST
- Corpo da Requisição: 
``` json
{
  "name": "John Doe",
  "username": "johndoe123",
  "email": "johndoe@example.com",
  "password": "001@Mypassword",
  "repeatPassword": "001@Mypassword"
}
```

### Resposta
- Código HTTP: 201
- Corpo da resposta: N/A

**Comment by alvarogfn** [comment]
eu quero!!!

**Comment by Frompaje** [comment]
Eu quero !!!

**Comment by Frompaje** [comment]
eu quero!!!
