### ISSUE TITLE
[Usuário][Cadastro] - Adicionar criptografia na senha do usuário

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost-backend#9]
Classe separada para encriptação

Quando a senha for cadastrada pelo usuário essa senha não pode ser salva como texto puro no banco, assim é preciso que seja encriptada antes de salvar.

Sugestões de libs de encriptação: `bcrypt`

**Comment by thiagoCalazans-dev** [comment]
EU QUERO!!!
